//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tier.Gui {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Recursos {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recursos() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tier.Gui.Recursos", typeof(Recursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se han configurado funcioalidades para la aplicación.
        /// </summary>
        internal static string ApplicacionSinFuncionalidades {
            get {
                return ResourceManager.GetString("ApplicacionSinFuncionalidades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se presentó un error mientras se procesaba la solicitud..
        /// </summary>
        internal static string ErrorGeneral {
            get {
                return ResourceManager.GetString("ErrorGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credenciales inválidas..
        /// </summary>
        internal static string InicioSesionNoUsuario {
            get {
                return ResourceManager.GetString("InicioSesionNoUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En un segundo serás redireccionado a la pagina principal. Feliz dia!.
        /// </summary>
        internal static string InicioSesionOk {
            get {
                return ResourceManager.GetString("InicioSesionOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No encontró un usuario con las credenciales suministradas..
        /// </summary>
        internal static string RestablecerClaveFallo {
            get {
                return ResourceManager.GetString("RestablecerClaveFallo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hemos enviado la nueva clave a tu correo electrónco..
        /// </summary>
        internal static string RestablecerClaveOk {
            get {
                return ResourceManager.GetString("RestablecerClaveOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se han configurado permisos para el rol asociado al usuario.
        /// </summary>
        internal static string RolSinPermisos {
            get {
                return ResourceManager.GetString("RolSinPermisos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertencia!.
        /// </summary>
        internal static string TituloNotificacionAdvertencia {
            get {
                return ResourceManager.GetString("TituloNotificacionAdvertencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        internal static string TituloNotificacionError {
            get {
                return ResourceManager.GetString("TituloNotificacionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correcto!.
        /// </summary>
        internal static string TituloNotificacionExitoso {
            get {
                return ResourceManager.GetString("TituloNotificacionExitoso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información.
        /// </summary>
        internal static string TituloNotificacionInformacion {
            get {
                return ResourceManager.GetString("TituloNotificacionInformacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensaje....
        /// </summary>
        internal static string TituloNotificacionMensaje {
            get {
                return ResourceManager.GetString("TituloNotificacionMensaje", resourceCulture);
            }
        }
    }
}
